services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./raw:/opt/airflow/raw
      - ./processed:/opt/airflow/processed
    command: airflow standalone