name: Prefect Modular PySpark ETL with Delta Lake

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Empty Folders
        run: |
          mkdir -p raw data/bronze data/silver data/gold processed/bronze processed/silver processed/gold

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Java (JRE) for PySpark
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre-headless
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      # 5. Lépés: Kényszerített griffe telepítés a Prefect belső hibájának elhárítására
      - name: Install Prefect, PySpark and Delta Lake
        run: |
          python -m pip install --upgrade pip
          pip install griffe==0.45.0 pydantic<2.0 prefect==2.14.21 pyspark==3.4.1 delta-spark==2.4.0

      - name: Run Prefect Medallion Pipeline
        run: |
          export PREFECT_API_URL=""
          python medallion_orchestrator.py
